manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001
  # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  # kinematics_solver_search_resolution: 0.005
  # kinematics_solver_timeout: 0.05
  # TRAC-IK 独有参数（可选）
  solve_type: Distance # 选项还有 Speed 或 Manipulation